# 判定順も下記順で行う　指定は正規表現も可
# メンション指定時の受け答え
mention: "@井口綾子"
respond: [
  {
    key: "deploy",
    msg: "おっけー deployね"
  },
]

# 特定のメッセージへの受け答え
hear: [
  { key: "おはよう", msg: "おはよう！" },
  { key: "調子どう？", msg: "まあまあかな" },
  { key: "疲れた", msg: "お疲れ様！" },
  { key: "越智って知ってる？", msg: "知ってる！\n「電大の生きる伝説」ですよね！" },
  { key: "内田って知ってる？", msg: "？" },
  { key: "デブって知ってる？", msg: "知ってる！\n「内田啓太」ですよね！" },
  { key: "^s?https?://[-_.!~*'()a-zA-Z0-9;/?:@&=+$,%#]+$", msg: "共有ありがとう！" },
]

# 特定のメッセージへのランダムな受け答え
hear_random: [
  {
    key: "今日の運勢は？",
    msg: [
      { text: "すごく良い！(๑´ڡ`๑)" },
      { text: "普通(´・ω・｀)" },
      { text: "あんま良くない(~_~;)" },
    ]
  },
]

# 全てのメッセージへの受け答え
all: 
  msg: [
    # { text: "？" },
  ]






